In [7]:
import numpy as np
#Пример срздания массивов:
lst1 = [1, 2, 3, 4, 5,6]
ar1 = np.array(lst1)
print(ar1)

matr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
print(matr)

zeroes = np.zeros(5)
print("Массив нулей: ")
print(zeroes)

zeroesMatr = np.zeros((3, 4))
print("Двуменрный массив нулей размером 3 на 5")
print(zeroesMatr)

ones  = np.ones(5)
print("Массив единиц: ")
print(ones)

orange = np.arange(10)
print("Массив до 10: ")
print(orange)

orangeStep = np.arange(0, 10 , 2)
print("С шагом 2: ")
print(orangeStep)

#форма и тип массивов
print("Тип данных: ")
print(orangeStep.dtype)
print("Форма: ")
print(orangeStep.shape)

#Получение по индексу и срезы
print("Первый элемент и последний: ")
print(orangeStep[0], orangeStep[-1])
print("Срез: " )
print(orangeStep[2:4])

print("Срез для двумерного массива: ")
print(matr[0:2, :])

#Векторные операции и базовые статистики
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

sm = arr2 + arr1 #Сложение
print("Сложение")
print(sm)

mult = arr1 * arr2
print("Умножение") #Умножение
print(mult)
#mean
print("Среднее по всем элементам: ")
print(np.mean(arr1))

[1 2 3 4 5 6]
[[1 2 3 4]
 [1 2 3 4]]
Массив нулей: 
[0. 0. 0. 0. 0.]
Двуменрный массив нулей размером 3 на 5
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив единиц: 
[1. 1. 1. 1. 1.]
Массив до 10: 
[0 1 2 3 4 5 6 7 8 9]
С шагом 2: 
[0 2 4 6 8]
Тип данных: 
int64
Форма: 
(5,)
Первый элемент и последний: 
0 8
Срез: 
[4 6]
Срез для двумерного массива: 
[[1 2 3 4]
 [1 2 3 4]]
Сложение
[11 22 33 44 55]
Умножение
[ 10  40  90 160 250]
Среднее по всем элементам: 
3.0
